version: 2.1
jobs:
  test:
    docker:
      - image: cimg/go:1.18.2
    steps:
      - checkout
      - run: go install
      - run: go test -v ./...
  build:
    docker:
      - image: cimg/go:1.18.2
    steps:
      - checkout
      - run: go install
      - run: go build
      - run: env GOOS=windows GOARCH=amd64 go build
      - persist_to_workspace:
          root: ./
          paths:
            - wake-on-lan
      - store_artifacts:
          path: /go/src/github.com/mylesnoton/wake-on-lan/wake-on-lan
          destination: wake-on-lan
      - store_artifacts:
          path: /go/src/github.com/mylesnoton/wake-on-lan/wake-on-lan.exe
          destination: wake-on-lan.exe
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - build
