name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.1'

    - name: Build
      run: go build -v ./...

    - name: Build EXE
      run: env GOOS=windows GOARCH=amd64 go build

    - name: Test
      run: go test -v ./...

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: |
          ./wake-on-lan
          ./wake-on-lan.exe